"""Constants shared across the app (status enums etc.)."""

from __future__ import annotations

from enum import Enum


class WebsiteStatus(str, Enum):
    HAS_WEBSITE = "HAS_WEBSITE"
    NO_WEBSITE = "NO_WEBSITE"
    UNKNOWN = "UNKNOWN"


class WebsiteQuality(str, Enum):
    EXCELLENT = "EXCELLENT"
    GOOD = "GOOD"
    AVERAGE = "AVERAGE"
    POOR = "POOR"
    UNKNOWN = "UNKNOWN"


class QualificationStatus(str, Enum):
    QUALIFIED = "QUALIFIED"
    NOT_QUALIFIED = "NOT_QUALIFIED"
    PENDING = "PENDING"


class OutreachStatus(str, Enum):
    NOT_CONTACTED = "NOT_CONTACTED"
    QUEUED = "QUEUED"
    APPROVED = "APPROVED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    REPLIED = "REPLIED"
    FAILED = "FAILED"
    STOPPED = "STOPPED"


class MessageStatus(str, Enum):
    DRAFT = "DRAFT"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    QUEUED = "QUEUED"
    SENDING = "SENDING"
    SCHEDULED = "SCHEDULED"
    SENT = "SENT"
    DELIVERED = "DELIVERED"
    REPLIED = "REPLIED"
    FAILED = "FAILED"
    RETRY_PENDING = "RETRY_PENDING"
    REJECTED = "REJECTED"
    EDITED = "EDITED"
    STOPPED = "STOPPED"


class ReplyClassification(str, Enum):
    POSITIVE = "POSITIVE"
    INTERESTED = "INTERESTED"
    QUESTION = "QUESTION"
    LATER = "LATER"
    NEGATIVE = "NEGATIVE"
    STOP = "STOP"
    UNKNOWN = "UNKNOWN"


class EventType(str, Enum):
    IMPORT = "IMPORT"
    QUALIFIED = "QUALIFIED"
    CAMPAIGN_CREATED = "CAMPAIGN_CREATED"
    MESSAGE_GENERATED = "MESSAGE_GENERATED"
    MESSAGE_APPROVAL_REQUESTED = "MESSAGE_APPROVAL_REQUESTED"
    MESSAGE_APPROVED = "MESSAGE_APPROVED"
    MESSAGE_REJECTED = "MESSAGE_REJECTED"
    MESSAGE_EDITED = "MESSAGE_EDITED"
    MESSAGE_SCHEDULED = "MESSAGE_SCHEDULED"
    MESSAGE_QUEUED = "MESSAGE_QUEUED"
    MESSAGE_SEND_STARTED = "MESSAGE_SEND_STARTED"
    MESSAGE_SENT = "MESSAGE_SENT"
    MESSAGE_DELIVERED = "MESSAGE_DELIVERED"
    MESSAGE_FAILED = "MESSAGE_FAILED"
    MESSAGE_RETRY_SCHEDULED = "MESSAGE_RETRY_SCHEDULED"
    FOLLOW_UP_CREATED = "FOLLOW_UP_CREATED"
    REPLY_RECEIVED = "REPLY_RECEIVED"
    REPLY_CLASSIFIED = "REPLY_CLASSIFIED"
    REPLY_DUPLICATE = "REPLY_DUPLICATE"
    LEAD_QUALIFIED = "LEAD_QUALIFIED"
    STOP_REQUEST = "STOP_REQUEST"
    LEAD_STOPPED = "LEAD_STOPPED"
    NOTIFICATION_SENT = "NOTIFICATION_SENT"
    ERROR = "ERROR"
    LEAD_UPDATED = "LEAD_UPDATED"
    DO_NOT_CONTACT = "DO_NOT_CONTACT"
    BACKUP_CREATED = "BACKUP_CREATED"


class IntelligenceStatus(str, Enum):
    NOT_ANALYZED = "NOT_ANALYZED"
    ANALYZED = "ANALYZED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    ERROR = "ERROR"